### PR TITLE
Task #6

### PR DESCRIPTION
**Pull request by LKeronen**
Live test page can be found at: "http://ric1.tursastin.net/test/scale/test.html". Conclusions in README.md.

### CODE REVIEW

**Comment by joonazan** [comment]
Needs further development. Does not communicate with our server and does not choose image properly yet.

This might help:
https://github.com/benlister/utilities/blob/master/Modernizr%20Retina%20:%20HiDPI%20test/hidpi_modernizr_test.js

`srcset` is the only correct way to do this IMO. Making the browser ask for a size is great! And it is supported in every browser I use at least: http://caniuse.com/#feat=srcset

**Comment by tursastin** [comment]
Task requires a technology that can be used to communicate with the server, not that we actually communicate with the server. Here the technology is to use logical screen dimensions and device pixel ratio to decide which image is delivered to the browser. This selection could be done either on client side or on server side.

We will investigate this a bit further and update the branch with latest findings.

**Comment by kmort89** [comment]
Is this research concluded or not?

**Comment by piiroim1** [comment]
Server can now return any image format supported by ImageMagick. The returned format is determined by the extension (e.g. 01.jpg or 01.webp ...).

test.html and test.js research\clientsideDPIdetection demonstrate how javascript can be used to determine supported formats and modify elements src -attribute by adding correct extension to the id. The demo site sets width and height parameters according to the size of the img element.

At the moment server does not support missing width or height and returns error if either of the parameters is missing. This should be fixed so in case one of the valies is missing decision is made based on the original image aspect ratio and if both are missing original image should be returned.

The missing functionality does not affect tasks #6.3 or #6.1 and therefore this pull request would complete these 2 tasks.

The functionality should be implemented for #6.3 though, which is scheduled for the Sprint 3.

**Pull request merged**
