### PR TITLE
Watermarking

### PR DESCRIPTION
**Pull request by hajoa**
Added watermarking configurable by .ini file and Conf struct with methods for reading values from configuration.

### CODE REVIEW

**Comment by joonazan** [comment]
All Get* functions return an error, except GetString, which just silently fails.

`server/config` and `server/configuration` contain the same Get* functions.

The Blob method of image should not destroy the image. It would break master.

"Watermark watermarks image" What a useless comment. And what do the arguments `horizontal` and `vertical` do?

The test is written as if Blob does not destroy the image. Which is good, because it shouldn't, as explained earlier.

The struct watermark should be capitalized and the fields that uniquely identify it should be capitalized. Only capitalized fields will be considered by the cache when looking if an equivalent transformation is already available.

You probably shouldn't read the minheight etc every time an image is watermarked. You also only check the last error on line 96 of urlparser.go. Probably you could somehow read the relevant part of the config into a global struct and then just use that?

**Comment by piiroim1** [comment]
There is no tests for Image.Watermark(), Watermarker or config!

There is no need to capitalize watermark - we agreed to handle cache key genration with GetKey() method so the watermark parameters do not need to be accessible from outside of the package. This is correct now.

**Comment by joonazan** [comment]
Errors are still not handled properly in the watermarking portion of urlparser. I still recommend parsing the config once and just using it in urlparser.

**Comment by joonazan** [comment]
Now errors are handled in a horribly repetitive manner, but at least they are handled properly. Paniccing is probably the right thing to do, though one might argue that watermarking should just be disabled if the config is broken.

**Pull request merged**
