### PR TITLE
Task #4 - Basic implementation of a HTTP Request handling server with image cache

### PR DESCRIPTION
**Pull request by kmort89**
@joonazan do you wish to peform the preview?

### CODE REVIEW

**Comment by kmort89** [comment]
The person who does the merge. You could use the command line option and "git merge --squash --no-ff TASK-#4" to squash all the commits into a single commit (saves space in the graphical layouts of git revision history).

**Comment by joonazan** [comment]
##This code needs to be improved:

The interface is unnecessary. It is not terrible, but I would use conditional compilation instead as there is no need for polymorphism. One benefit is that it would make profiling different versions with benchmark tests dead simple.

###GetImage:
- should not take width and height as pointers. They not being given will be expressed elsewhere more naturally. Using zero to mean not set would also be _better_ although it would not be _good_.
- should not write to the log for each path tried for performance and usefullness reasons.
- named return values do what you're doing on line 19 and 20, only better.
- error handling is super messy. Line 31 thru 33 could maybe be removed as it is a bit redundant.

###AddRoot:
- the test at the start is useless; it should compare abspath, not fileroot

###RemoveRoot:
- what memory leak? I see none.

###MyHandler:
- unnecessary and unhelpful comments. (lines 21, 24, 27), while roots in Cacheless should be commented.
- cacher should not be a __pointer to an interface__. Interfaces are reference types. You're essentially making a pointer to a pointer.
- booleans are Evil. Use conditional compilation: make a file with a function that prints and another that does nothing. Put `//+build debug` at the beginning of one and `//+build !debug` at the beginning of the other.
- started is never used and seems to be some other thing's responsibility anyway.

###ServeHTTP:
- maybe too much nesting
- do not dereference pointers when it is not necessary. Here it is not that bad, but in other cases it makes changing code a bit harder.
- Go has escape analysis! No need to try to allocate on the heap as if this was C. Just do `width = &intw`. (`intw` is already an `uint64`.) Actually we should probably use `uint32` for image dimensions. It is definitely large enough.
- change `self` to `h`. Do not dereference it! (With this struct switching to a non-pointer receiver would be pretty reasonable.)

###RetrieveHello:
- use `io.WriteString`. It is more robust.
- make it a function instead of a method

###RetrieveImage:
- here the Write-method is used correctly. io.Copy would probably perform worse.
- still many unnecessary dereferences and `self`

###NewServer:
- `new` is only useful on structs, and even with them __`&Structname{}` is equivalent__. Try `cacher := new(Cacheless)`. You don't even need to cast it to `ImageCache`.
- 

Finally, remove the _obvious_ comment preceding main.

**Comment by kmort89** [comment]
## Reply
The interface stays. The polymorphisims comes from mocking. In addition to having the implementation (for example cacheless) extend the interface, the mock implementation will also extend it (for example cachelessMock in a server test).

### GetImage
- I wanted to make distinction between "?width=0&height=0" case and the case were they are not given. I agree that this can be moved to elsewhere.

- Cacheless is a prototype which will be discarded during the project (or atleast deprecated). It has absolutely zero performance requirements, therefore the log messages stay there.

- Named return values utilized.

- I think you missed the loop, if the file is not found under a certain root it will print not found and CONTINUE looping. If the error is something else (no read permission etc) then it will instantly return with the error value.

### AddRoot
- Good catch

### RemoveRoot
- The link explains the possible leak, basically the slice still contain references to the elementes outside the slice after that operation (something to do with the internal implementation of slices).

### MyHandler
- The comments stay as long as the functionality is there.

- Interface pointer fixed.

- This is what my TODO comment meant about the preprocessor. Implemented per instructions.

- Started stays since we might use it in tests also and we can gather light weight statistics with it even on production environment.

### ServeHTTP
- Ignored nesting for now, this can be refactored later when we have better understanding of the rest of program and where to do this.

- Fine, it appears the ReviewComments did agree on this.

- I want the code to use uint32 on 32-bit platforms and uint64 on 64-bit platforms => therefore, uint is the most logical solution. However, it appears that ParseUint will always return uint64, even if I dictate that only 32-bits should be returned. Sounds like a cast will need to happend anyways.

- ReviewComments linkistä: "If the method needs to mutate the receiver, the receiver must be a pointer."

### RetrieveHello
- io.WriteString utilized

- It will stay as a method for now, since we will probably want to do more elegant test cases and we will probably need access to handler for that.

### RetriveImage
- Fixed some selfs and dereferences.

### NewServer
- Refactored.

-----------
Pushed a new version (please comment further, or accept the pull request).

**Comment by piiroim1** [comment]
### GetImage

Pointer types for width and height remains. Is there abetter way to handle requests without these values than using nil for indicating missing value? Not a major problem but we might want to change this later.

### Other


The code seems fine. Tee.do task #4 isn't yet fulfilled. According to the feature description the image associated with the requested id should be fetched from a second web server that serves a flat filesystem (or from cache but it will be implemented later).

Unit test testing that correct image is returned should be created.

Currently LoadImage loads image associated with the id from the local filesystem, which is not sufficient for task #4. New functionality should be implemented for fetching the image from second web server instead of local filesystem.

Described functionality needs to be implemented to complete #4. It might also be neccessary to split the task #4.

**Pull request merged**
