### PR TITLE
Deny upscaling

### PR DESCRIPTION
**Pull request by LKeronen**
Server no longer upscales images.

### CODE REVIEW

**Comment by tursastin** [comment]
Image data is loaded twice when first accessing an image.

DenyUpScale.GetImage calls:

1) ImageSize to get image dimensions. Resizer implementation caches results for further calls with the same image name. It will however need to load the image into memory for the first call.

2) GetImage to retrieve processed image data. NewBasicResizer implementation caches original image data for further calls with the same image name. It will however need to load image when first accessed or if data has been evicted from the cache.

DenyUpScale thus has worse performance on first call for each image than the previous implementation.

**Comment by joonazan** [comment]
The performance is worse *on the first time* if *both width and height are set*. This is pretty rare.

**Comment by kmort89** [comment]
That is not rare, it is very normal use-case.

**Comment by joonazan** [comment]
Well, I would assume that each image is served more than once. First time here means first time for a particular source image, not output size and source image.

**Pull request merged**
