### PR TITLE
Support incomplete params

### PR DESCRIPTION
**Pull request by piiroim1**
Added support for requesting images by providing only one either width or height. The image will be scaled according to the original aspect ratio. Requesting without parameters returns original sized image. Requesting without extension returns original image.

+ Lots of refactoring and tests for the new stuff.

### CODE REVIEW

**Comment by joonazan** [comment]
There is way too much code duplication in GetImageBy{Width, Height} & co of Cache.

Resize logic is duplicated in Cache and Cacheless.

If you claim that there is any virtue in code duplication, please note that you have described GetOriginalSizedImage of Cacheless with "Returns image by height only. The image is scaled and aspect ratio preserved". *Duplicated code means that to change one thing, you need to change code in a dozen places.* I hope everyone agrees that this is highly undesirable.

Kristian said that Cache should not depend on Cacheless, but IMO the only other acceptable solution is to make both use the same functions or embed the same struct.

**Comment by piiroim1** [comment]
Yeah, I agree on this

I can work on this next week if anyone alse has not by then.

**Comment by joonazan** [comment]
I will split the functionality into three responsibilities: image resizing, caching and handling of incomplete size.

**Comment by joonazan** [comment]
Something is horribly wrong with GetImageByHeight and Width. They divide and then multiply with the same value. Will write test that proves them erroneous.

**Comment by joonazan** [comment]
Now I am okay with this. Only improvement I can think of is removing duplication in the aspect ratio code.

**Comment by joonazan** [comment]
It might make sense to make two interfaces:
- Resizer for lets you query original size and request a resized image
- Adding and removing roots and such would be behind another interface

Size guessing uses an if to select a method at the moment, but the if could be inside a single method, which would make things a lot more concise.

**Comment by kmort89** [comment]
Roots are supposed to be under filesystem anyways. The solution was temporary even in the beginning.

**Pull request merged**
